### ISSUE TITLE
Does user tagger toggle button need extra styling?

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2696]
https://www.reddit.com/r/RESissues/comments/43bdjo/bug_option_for_ignore_in_night_mode_tag_flyout_is/

```css
#userTaggerToolTip .toggleButton.enabled .toggleOn {
    background-color: #DDD;
    color: #636363;
}
#userTaggerToolTip .toggleButton .toggleOn {
    background-color: #107AC4;
    color: #FFF;
}
```
