### ISSUE TITLE
The highlight color when using keyboard navigation seems broken and overrides my css file.

### ISSUE THREAD

**Issue by justinjk007** [honestbleeps/Reddit-Enhancement-Suite#4638]
Hi, I am one of the moderators of [r/linuxhardware](https://www.reddit.com/r/linuxhardware ) , I am using RES **v5.10.1** . 

Google Chrome | 63.0.3239.132 (Official Build) (64-bit) (cohort: Stable), on Windows 10.

Today I was browsing the subreddit and saw that the highlighted element when using keyboard to navigate the website is white which is very contrasting to our dark theme and I can't seem to override it. This is what it looks like now
![image](https://user-images.githubusercontent.com/12916795/34910350-ff1ee7b0-f880-11e7-8006-e47adfec63c3.png)

In the debugging window I can see that somehow this thing is clearly overriding my css file somehow

![image](https://user-images.githubusercontent.com/12916795/34910359-222fd656-f881-11e7-994c-38d894a5df9f.png)

I tried using this snippet from [this](https://www.reddit.com/r/Enhancement/wiki/subredditstyling) snippet from **r/Enhancemnt** but it is not working for me.
```css
.res .RES-keyNav-activeElement,
.res .commentarea .RES-keyNav-activeElement .md,
.res .RES-keyNav-activeElement .md-container, 
.res .commentarea .RES-keyNav-activeElement.entry .noncollapsed {
    background: #cacaca !important;
}
```

and I can't even find any place in my css file where I am using this white color, soo.. can somebody help me out.

**Comment by larsjohnsen** [comment]
That snippet appears to be a little out of date. RES changed the class with which it styles the selected element to '.res-selected' (though the earlier is kept, though you may have to increase the specificity in the selector). In your instance, it would suffice to change `.RES-keyNav-activeElement` to `.entry..RES-keyNav-activeElement`.

**Comment by justinjk007** [comment]
OK tried it but as you can see here the white color is still over-riding my css file.
![image](https://user-images.githubusercontent.com/12916795/34948968-aafa9032-f9dc-11e7-8715-bd872f057feb.png)

**Comment by justinjk007** [comment]
I also tried 
```css
.entry.RES-keyNav-activeElement .md-container {
    background-color: #434b55 !important;
}
```
No change what so-ever

**Comment by larsjohnsen** [comment]
I see that you removed `.res` from that selector, which lowers its specificity.

**Comment by justinjk007** [comment]
so what will be correct snippet then ?

**Comment by justinjk007** [comment]
Thank you very much
```css
.res .entry.RES-keyNav-activeElement {
    background-color: #434b55 !important;
}
```
This fixed it
